# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: OpenAI:gpt-4.1-mini
clients:
- type: openai-compatible
  name: OpenAI
  api_base: https://models.inference.ai.azure.com
  models:
  - name: gpt-4.1-mini
    max_input_tokens: 8000
